apiVersion: v1
kind: Service
metadata:
  name: mypod
  namespace: open5gs-k8s
  labels:
    component: mypod
spec:
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060
  selector:
    component: mypod