apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: ricaportela/docker_kamailio
    imagePullPolicy: Always
    command: ["echo", "SUCCESS"]